---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- build/**/*
- data/**/*
- tasks/**/*
- tmp/**/*
domains: []
reporters:
- typecheck
- rubocop
# - typecheck:strict
require:
- minitest
- minitest/autorun
max_files: 5000
