module Eddy
  module Elements
    # ### Element Summary:
    #
    # - Id: I08
    # - Name: Interchange Date
    # - Type: DT (YYMMDD)
    # - Min/Max: 6/6
    # - Description: Date of the interchange
    #
    # ### Notes:
    #
    # This element's value will be generated by `Eddy`.
    # No call to `value=` is needed.
    class I08 < Eddy::Element::DT
      # @param val [Time]
      # @param req [Boolean] (nil)
      # @return [void]
      def initialize(val:, req: nil)
        @id = "I08"
        @name = "Interchange Date"
        @description = "Date of the interchange"
        self.fmt = :yymmdd
        super(
          min: 6,
          max: 6,
          req: req,
          val: val,
        )
      end
    end
  end
end
