require "time"

module Eddy
  module Elements
    # ### Element Summary:
    #
    # - Id: I09
    # - Name: Interchange Time
    # - Type: TM (HHMM)
    # - Min/Max: 4/4
    # - Description: Time of the interchange
    #
    # ### Notes:
    #
    # This element's value will be generated by `Eddy`.
    # No call to `value=` is needed.
    class InterchangeTime < Eddy::Element::TM
      # @return [void]
      def initialize()
        @id = "I09"
        @name = "Interchange Time"
        super(
          min: 4,
          max: 4,
          fmt: :hhmm,
          val: Time.now.utc,
        )
      end
    end
  end
end
